# Generated by Django 4.2.7 on 2023-11-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('empty', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Available lockers left'), ('Maintanence', 'Not available'), ('Closed', 'No lockers left')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('paid', models.BooleanField(default=False)),
                ('placedOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('Preparing', 'At storage house'), ('Arriving', 'Riding to the locker'), ('Arrived', 'Waiting at the parcel locker'), ('Delivered', 'Found new home')], max_length=20)),
                ('locker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='parcify_app.locker')),
            ],
        ),
        migrations.AddField(
            model_name='locker',
            name='parcelLocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parcify_app.parcellocker'),
        ),
    ]
